version: '3.7'
volumes:
  pgdata_development: {}
  logs_development: {}
services:
  app:
    platform: linux/x86_64 # specify the architecture here
    container_name: jenkins-test-spring-boot
    image: jenkins-test-spring-boot
    build: ./
    ports:
      - 3030:3030
    volumes:
      - type: bind
        source: /var/log/cdpdashboard
        target: /var/log/cdpdashboard